#The coordinates where the player will be teped when leaving the end (Para salir del end debe entrar en agua)
random-coords: 300, 70, 300
# # # # # # # # # # # # # #

end-world-name: 'end-world'
end-spawn-coords: 100, 100 , 100
nether-world-name: 'nether-world'
nether-spawn-coords: 100, 100, 100

#Icon for colors: "§"
error-msg: '§c An error has occurred !'
succes-msg: '§a You have been successfully teleported to {world}.'

#Recuerda cargar tus mundos con tu plugin de creacion de mundos (/mw load yourname)